from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import shutil
import stat
import tempfile
import zipfile

from .model import Device
from .manifest import DEFAULT_LIBRARY_FOLDERS
from .safety import (
    SafetyError,
    fsync_directory,
    fsync_file,
    require_directory,
    under,
)
from .ssh import read_authorized_key


LAUNCH_MODES = {"autostart", "nickelmenu"}
NICKELMENU_CONFIG = """# Generated by koreader-appliance.
menu_item:main:KOReader:cmd_spawn:quiet:exec /bin/sh /mnt/onboard/.adds/nm/koreader-launch.sh
"""
NICKELMENU_LAUNCHER = """#!/bin/sh
set -eu

for root in /mnt/onboard/.adds/koreader /mnt/onboard/.adds/koreader.previous; do
    if [ -f "$root/koreader.sh" ]; then
        exec /bin/sh "$root/koreader.sh"
    fi
done

exit 1
"""
DEPLOYMENT_MARKER = ".koreader-appliance.json"
MUTABLE_ENTRIES = (
    "cache",
    "clipboard",
    "data",
    "docsettings",
    "hashdocsettings",
    "history",
    "patches",
    "screenshots",
    "settings",
    "settings.reader.lua",
    "styletweaks",
)


def _safe_zip_members(archive: zipfile.ZipFile) -> list[zipfile.ZipInfo]:
    members = archive.infolist()
    for member in members:
        path = PurePosixPath(member.filename)
        mode = member.external_attr >> 16
        if path.is_absolute() or ".." in path.parts or stat.S_ISLNK(mode):
            raise SafetyError(
                f"archive member escapes extraction root: {member.filename}"
            )
    return members


def _find_koreader_root(extracted: Path) -> Path:
    for candidate in (extracted / ".adds" / "koreader", extracted / "koreader"):
        if (candidate / "reader.lua").is_file():
            return candidate
    matches = [path.parent for path in extracted.rglob("reader.lua")]
    if len(matches) != 1:
        raise SafetyError(
            "KOReader archive does not contain one identifiable reader.lua"
        )
    return matches[0]


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _tree_hash(root: Path) -> str:
    digest = hashlib.sha256()
    if not root.is_dir():
        return digest.hexdigest()
    for path in sorted(item for item in root.rglob("*") if item.is_file()):
        relative = path.relative_to(root).as_posix().encode()
        digest.update(len(relative).to_bytes(4, "big"))
        digest.update(relative)
        with path.open("rb") as handle:
            for block in iter(lambda: handle.read(1024 * 1024), b""):
                digest.update(block)
    return digest.hexdigest()


def _overlay_root(device: Device) -> Path:
    return device.source.parent / "onboard"


def deployment_record(
    device: Device, archive_sha256: str, launch_mode: str
) -> dict[str, object]:
    return {
        "schema": 1,
        "device": device.id,
        "archive_sha256": archive_sha256,
        "overlay_sha256": _tree_hash(_overlay_root(device)),
        "launch_mode": launch_mode,
    }


def deployment_is_current(
    destination: Path,
    device: Device,
    archive_sha256: str,
    launch_mode: str,
) -> bool:
    marker = destination / DEPLOYMENT_MARKER
    if not marker.is_file():
        return False
    try:
        actual = json.loads(marker.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return False
    return actual == deployment_record(device, archive_sha256, launch_mode)


def _copy_mutable_state(current: Path, staging: Path) -> None:
    if not current.is_dir():
        return
    for name in MUTABLE_ENTRIES:
        source = current / name
        target = staging / name
        if source.is_dir():
            shutil.copytree(
                source, target, dirs_exist_ok=True, copy_function=shutil.copy2
            )
        elif source.is_file():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)


def _copy_onboard_overlay(staging: Path, device: Device) -> None:
    overlay = _overlay_root(device)
    if not overlay.is_dir():
        return
    koreader_overlay = overlay / device.storage.koreader_root
    if koreader_overlay.is_dir():
        shutil.copytree(
            koreader_overlay,
            staging,
            dirs_exist_ok=True,
            copy_function=shutil.copy2,
        )


def _fsync_tree(root: Path) -> None:
    for path in sorted(root.rglob("*"), reverse=True):
        if path.is_file():
            fsync_file(path)
        elif path.is_dir():
            fsync_directory(path)
    fsync_directory(root)


def _atomic_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".new")
    temporary.write_text(content, encoding="utf-8")
    fsync_file(temporary)
    os.replace(temporary, path)
    fsync_directory(path.parent)


def _atomic_copy(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(destination.name + ".new")
    shutil.copy2(source, temporary)
    fsync_file(temporary)
    os.replace(temporary, destination)
    fsync_directory(destination.parent)


def _activate_staging(staging: Path, destination: Path) -> None:
    previous = destination.with_name(destination.name + ".previous")
    if previous.exists():
        shutil.rmtree(previous)
    if destination.exists():
        destination.rename(previous)
    try:
        staging.rename(destination)
    except BaseException:
        if previous.exists() and not destination.exists():
            previous.rename(destination)
        raise
    fsync_directory(destination.parent)


def stage_koreader(
    mount: Path,
    archive_path: Path,
    root_package: Path,
    device: Device,
    settings: Path | None = None,
    folders: tuple[str, ...] = DEFAULT_LIBRARY_FOLDERS,
    launch_mode: str = "autostart",
    authorized_key: Path | None = None,
) -> dict[str, str]:
    mount = require_directory(mount, "reader mount")
    if not device.matches(mount):
        raise SafetyError(f"{mount} does not match adapter {device.id}")
    if not archive_path.is_file() or not root_package.is_file():
        raise SafetyError(
            "KOReader archive and root package must both be readable files"
        )
    if launch_mode not in LAUNCH_MODES:
        raise SafetyError(f"unsupported KOReader launch mode: {launch_mode}")

    archive_hash = _sha256(archive_path)
    destination = under(mount, device.storage.koreader_root)
    destination.parent.mkdir(parents=True, exist_ok=True)
    redeployed = not deployment_is_current(
        destination, device, archive_hash, launch_mode
    )

    if redeployed:
        staging = destination.with_name(destination.name + ".staging")
        if staging.exists():
            shutil.rmtree(staging)
        with tempfile.TemporaryDirectory(
            prefix="koreader-appliance-stage-"
        ) as temporary:
            extracted = Path(temporary)
            with zipfile.ZipFile(archive_path) as archive:
                archive.extractall(extracted, members=_safe_zip_members(archive))
            source = _find_koreader_root(extracted)
            shutil.copytree(source, staging, copy_function=shutil.copy2)

        _copy_onboard_overlay(staging, device)
        _copy_mutable_state(destination, staging)
        if not (staging / "reader.lua").is_file() or not (
            staging / "koreader.sh"
        ).is_file():
            raise SafetyError("staged KOReader tree is incomplete")

        marker = staging / DEPLOYMENT_MARKER
        marker.write_text(
            json.dumps(
                deployment_record(device, archive_hash, launch_mode),
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )
        _fsync_tree(staging)
        _activate_staging(staging, destination)

    trigger = under(mount, device.storage.installer_trigger)
    _atomic_copy(root_package, trigger)

    source_hash = _sha256(root_package)
    staged_hash = _sha256(trigger)
    if source_hash != staged_hash:
        raise OSError("root package changed while staging")

    books_root = under(mount, device.storage.books_root)
    for directory in folders:
        (books_root / directory).mkdir(parents=True, exist_ok=True)

    staged_settings = "not-requested"
    if settings is not None:
        settings = settings.expanduser().resolve()
        if not settings.is_file():
            raise SafetyError(f"KOReader settings profile is not readable: {settings}")
        settings_target = destination / (
            "settings.reader.lua.pending"
            if launch_mode == "autostart"
            else "settings.reader.lua"
        )
        if launch_mode == "nickelmenu" and settings_target.exists():
            staged_settings = "preserved-existing"
        else:
            _atomic_copy(settings, settings_target)
            staged_settings = str(settings_target)

    authorized_keys = None
    if authorized_key is not None:
        authorized_keys = destination / "settings/SSH/authorized_keys"
        _atomic_text(authorized_keys, read_authorized_key(authorized_key))

    launcher_config = "not-applicable"
    if device.platform == "kobo" and launch_mode == "nickelmenu":
        launcher = under(mount, ".adds/nm/koreader")
        _atomic_text(launcher, NICKELMENU_CONFIG)
        launcher_script = under(mount, ".adds/nm/koreader-launch.sh")
        _atomic_text(launcher_script, NICKELMENU_LAUNCHER)
        launcher_config = str(launcher)

    ssh_enabled = None
    if device.platform == "kobo" and launch_mode == "autostart":
        ssh_enabled = under(mount, ".kobo/ssh-enabled")
        ssh_enabled.write_text(
            "Key-only SSH enabled by koreader-appliance.\n",
            encoding="utf-8",
        )
        fsync_file(ssh_enabled)
    return {
        "koreader_root": str(destination),
        "installer_trigger": str(trigger),
        "installer_sha256": staged_hash,
        "ssh_enabled_marker": str(ssh_enabled)
        if ssh_enabled is not None
        else "not-applicable",
        "launch_mode": launch_mode,
        "launcher_config": launcher_config,
        "redeployed": str(redeployed).lower(),
        "authorized_keys": str(authorized_keys)
        if authorized_keys is not None
        else "not-requested",
        "settings_pending": staged_settings,
    }
