from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import shutil
import stat
import tarfile
import tempfile
import zipfile

from .model import Device
from .manifest import DEFAULT_LIBRARY_FOLDERS
from .safety import (
    SafetyError,
    fsync_directory,
    fsync_file,
    require_directory,
    under,
)
from .ssh import read_authorized_key


LAUNCH_MODES = {"autostart", "nickelmenu"}
NICKELMENU_CONFIG = """# Generated by koreader-appliance.
menu_item:main:KOReader:cmd_spawn:quiet:exec /bin/sh /mnt/onboard/.adds/koreader-appliance/koreader-launch.sh
"""
NICKELMENU_LAUNCHER = """#!/bin/sh
set -eu

for root in /mnt/onboard/.adds/koreader /mnt/onboard/.adds/koreader.previous; do
    if [ -f "$root/koreader.sh" ]; then
        if /bin/sh "$root/koreader.sh"; then
            status=0
        else
            status=$?
        fi

        # Return code 88 means KOReader already asked the OS to shut down.
        # Every other final exit cold-boots Nickel so NickelMenu is loaded by
        # the normal firmware startup path instead of an in-process restart.
        if [ "$status" -ne 88 ]; then
            sync
            /sbin/reboot
        fi
        exit "$status"
    fi
done

exit 1
"""
DEPLOYMENT_MARKER = ".koreader-appliance.json"
LIBRARY_MARKER = ".adds/koreader-appliance/library.json"
EXCLUDE_SYNC_FOLDERS = r"(\.(?!kobo|adobe).+|([^.][^/]*/)+\..+)"
BOOK_SUFFIXES = {
    ".cbr",
    ".cbz",
    ".chm",
    ".djvu",
    ".docx",
    ".epub",
    ".fb2",
    ".html",
    ".mobi",
    ".pdf",
    ".rtf",
    ".txt",
}
STATE_ENTRIES = (
    "clipboard",
    "data",
    "docsettings",
    "hashdocsettings",
    "history",
    "screenshots",
    "settings",
    "settings.reader.lua",
    "styletweaks",
)


def _safe_zip_members(archive: zipfile.ZipFile) -> list[zipfile.ZipInfo]:
    members = archive.infolist()
    for member in members:
        path = PurePosixPath(member.filename)
        mode = member.external_attr >> 16
        if path.is_absolute() or ".." in path.parts or stat.S_ISLNK(mode):
            raise SafetyError(
                f"archive member escapes extraction root: {member.filename}"
            )
    return members


def _find_koreader_root(extracted: Path) -> Path:
    for candidate in (extracted / ".adds" / "koreader", extracted / "koreader"):
        if (candidate / "reader.lua").is_file():
            return candidate
    matches = [path.parent for path in extracted.rglob("reader.lua")]
    if len(matches) != 1:
        raise SafetyError(
            "KOReader archive does not contain one identifiable reader.lua"
        )
    return matches[0]


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _tree_hash(root: Path) -> str:
    digest = hashlib.sha256()
    if not root.is_dir():
        return digest.hexdigest()
    for path in sorted(item for item in root.rglob("*") if item.is_file()):
        relative = path.relative_to(root).as_posix().encode()
        digest.update(len(relative).to_bytes(4, "big"))
        digest.update(relative)
        with path.open("rb") as handle:
            for block in iter(lambda: handle.read(1024 * 1024), b""):
                digest.update(block)
    return digest.hexdigest()


def _overlay_root(device: Device) -> Path:
    return device.source.parent / "onboard"


def deployment_record(
    device: Device,
    archive_sha256: str,
    launch_mode: str,
    syncthing_plugin_sha256: str | None = None,
    syncthing_binary_sha256: str | None = None,
    state_backup_sha256: str | None = None,
) -> dict[str, object]:
    return {
        "schema": 3,
        "device": device.id,
        "archive_sha256": archive_sha256,
        "overlay_sha256": _tree_hash(_overlay_root(device)),
        "launch_mode": launch_mode,
        "syncthing_plugin_sha256": syncthing_plugin_sha256,
        "syncthing_binary_sha256": syncthing_binary_sha256,
        "state_backup_sha256": state_backup_sha256,
    }


def deployment_is_current(
    destination: Path,
    device: Device,
    archive_sha256: str,
    launch_mode: str,
    syncthing_plugin_sha256: str | None = None,
    syncthing_binary_sha256: str | None = None,
    state_backup_sha256: str | None = None,
) -> bool:
    marker = destination / DEPLOYMENT_MARKER
    if not marker.is_file():
        return False
    try:
        actual = json.loads(marker.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return False
    return actual == deployment_record(
        device,
        archive_sha256,
        launch_mode,
        syncthing_plugin_sha256,
        syncthing_binary_sha256,
        state_backup_sha256,
    )


def _install_syncthing(
    staging: Path, plugin_archive: Path, binary_archive: Path
) -> None:
    with tempfile.TemporaryDirectory(prefix="koreader-syncthing-") as temporary:
        extracted = Path(temporary)
        with zipfile.ZipFile(plugin_archive) as archive:
            archive.extractall(extracted, members=_safe_zip_members(archive))
        candidates = ([extracted] if (extracted / "main.lua").is_file() else []) + [
            path.parent
            for path in extracted.rglob("main.lua")
            if path.parent.name == "kosyncthing_plus.koplugin"
        ]
        if len(candidates) != 1:
            raise SafetyError("Syncthing plugin archive has no unique plugin root")
        destination = staging / "plugins/kosyncthing_plus.koplugin"
        shutil.copytree(candidates[0], destination, dirs_exist_ok=True)

    with tarfile.open(binary_archive, "r:gz") as archive:
        candidates = []
        for member in archive.getmembers():
            path = PurePosixPath(member.name)
            if path.is_absolute() or ".." in path.parts or member.issym() or member.islnk():
                raise SafetyError(
                    f"Syncthing archive member is unsafe: {member.name}"
                )
            if (
                member.isfile()
                and path.name == "syncthing"
                and len(path.parts) == 2
            ):
                candidates.append(member)
        if len(candidates) != 1:
            raise SafetyError("Syncthing archive has no unique binary")
        source = archive.extractfile(candidates[0])
        if source is None:
            raise SafetyError("Syncthing binary could not be read")
        binary = staging / "plugins/kosyncthing_plus.koplugin/syncthing"
        with binary.open("wb") as target:
            shutil.copyfileobj(source, target)
        binary.chmod(0o755)


def _copy_state(source_root: Path | None, staging: Path) -> None:
    if source_root is None or not source_root.is_dir():
        return
    for name in STATE_ENTRIES:
        source = source_root / name
        target = staging / name
        if source.is_dir():
            shutil.copytree(
                source, target, dirs_exist_ok=True, copy_function=shutil.copyfile
            )
        elif source.is_file():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, target)


def _copy_onboard_overlay(staging: Path, device: Device) -> None:
    overlay = _overlay_root(device)
    if not overlay.is_dir():
        return
    koreader_overlay = overlay / device.storage.koreader_root
    if koreader_overlay.is_dir():
        shutil.copytree(
            koreader_overlay,
            staging,
            dirs_exist_ok=True,
            copy_function=shutil.copyfile,
        )


def _fsync_tree(root: Path) -> None:
    for path in sorted(root.rglob("*"), reverse=True):
        if path.is_file():
            fsync_file(path)
        elif path.is_dir():
            fsync_directory(path)
    fsync_directory(root)


def _atomic_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".new")
    temporary.write_text(content, encoding="utf-8")
    fsync_file(temporary)
    os.replace(temporary, path)
    fsync_directory(path.parent)


def _atomic_copy(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(destination.name + ".new")
    shutil.copyfile(source, temporary)
    fsync_file(temporary)
    os.replace(temporary, destination)
    fsync_directory(destination.parent)


def _set_ini_value(path: Path, section: str, key: str, value: str) -> None:
    lines = path.read_text(encoding="utf-8").splitlines() if path.is_file() else []
    header = f"[{section}]"
    start = next((i for i, line in enumerate(lines) if line.strip() == header), None)
    if start is None:
        if lines and lines[-1]:
            lines.append("")
        lines.extend((header, f"{key}={value}"))
    else:
        end = next(
            (i for i in range(start + 1, len(lines)) if lines[i].startswith("[")),
            len(lines),
        )
        current = next(
            (
                i
                for i in range(start + 1, end)
                if lines[i].split("=", 1)[0].strip() == key
            ),
            None,
        )
        if current is None:
            lines.insert(end, f"{key}={value}")
        else:
            lines[current] = f"{key}={value}"
    _atomic_text(path, "\n".join(lines) + "\n")


def _library_files(source: Path) -> list[Path]:
    if not source.is_dir():
        raise SafetyError(f"library restore source is not a directory: {source}")
    return sorted(
        path
        for path in source.rglob("*")
        if path.is_file()
        and path.suffix.lower() in BOOK_SUFFIXES
        and not any(part.startswith(".") for part in path.relative_to(source).parts)
        and "migration-artifacts" not in path.relative_to(source).parts
    )


def library_tree_hash(source: Path) -> tuple[str, int]:
    digest = hashlib.sha256()
    files = _library_files(source)
    for path in files:
        relative = path.relative_to(source).as_posix().encode()
        digest.update(len(relative).to_bytes(4, "big"))
        digest.update(relative)
        with path.open("rb") as handle:
            for block in iter(lambda: handle.read(1024 * 1024), b""):
                digest.update(block)
    return digest.hexdigest(), len(files)


def library_is_current(mount: Path, expected: str) -> bool:
    marker = under(mount, LIBRARY_MARKER)
    try:
        record = json.loads(marker.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return False
    return record.get("schema") == 1 and record.get("sha256") == expected


def _restore_library(mount: Path, books_root: Path, source: Path, expected: str) -> None:
    actual, count = library_tree_hash(source)
    if actual != expected:
        raise SafetyError(
            f"library restore SHA-256 mismatch: expected {expected}, got {actual}"
        )
    for path in _library_files(source):
        target = books_root / path.relative_to(source)
        if not target.is_file() or _sha256(target) != _sha256(path):
            _atomic_copy(path, target)
    marker = under(mount, LIBRARY_MARKER)
    record = {"schema": 1, "sha256": actual, "files": count}
    _atomic_text(marker, json.dumps(record, sort_keys=True) + "\n")


def _remove_macos_metadata(*roots: Path) -> None:
    for root in roots:
        if not root.is_dir():
            continue
        for directory, _, files in os.walk(root, onerror=lambda _: None):
            for name in files:
                if name.startswith("._") or name == ".DS_Store":
                    Path(directory, name).unlink(missing_ok=True)


def _activate_staging(staging: Path, destination: Path) -> None:
    previous = destination.with_name(destination.name + ".previous")
    if previous.exists():
        shutil.rmtree(previous)
    if destination.exists():
        destination.rename(previous)
    try:
        staging.rename(destination)
    except BaseException:
        if previous.exists() and not destination.exists():
            previous.rename(destination)
        raise
    fsync_directory(destination.parent)


def stage_koreader(
    mount: Path,
    archive_path: Path,
    root_package: Path,
    device: Device,
    settings: Path | None = None,
    folders: tuple[str, ...] = DEFAULT_LIBRARY_FOLDERS,
    launch_mode: str = "autostart",
    authorized_key: Path | None = None,
    library_source: Path | None = None,
    library_sha256: str | None = None,
    syncthing_plugin: Path | None = None,
    syncthing_binary: Path | None = None,
    state_source: Path | None = None,
    state_backup_sha256: str | None = None,
) -> dict[str, str]:
    mount = require_directory(mount, "reader mount")
    if not device.matches(mount):
        raise SafetyError(f"{mount} does not match adapter {device.id}")
    if not archive_path.is_file() or not root_package.is_file():
        raise SafetyError(
            "KOReader archive and root package must both be readable files"
        )
    if launch_mode not in LAUNCH_MODES:
        raise SafetyError(f"unsupported KOReader launch mode: {launch_mode}")

    archive_hash = _sha256(archive_path)
    if (syncthing_plugin is None) != (syncthing_binary is None):
        raise SafetyError("Syncthing plugin and binary archives must be set together")
    syncthing_plugin_hash = _sha256(syncthing_plugin) if syncthing_plugin else None
    syncthing_binary_hash = _sha256(syncthing_binary) if syncthing_binary else None
    destination = under(mount, device.storage.koreader_root)
    destination.parent.mkdir(parents=True, exist_ok=True)
    redeployed = not deployment_is_current(
        destination,
        device,
        archive_hash,
        launch_mode,
        syncthing_plugin_hash,
        syncthing_binary_hash,
        state_backup_sha256,
    )

    if redeployed:
        staging = destination.with_name(destination.name + ".staging")
        if staging.exists():
            shutil.rmtree(staging)
        with tempfile.TemporaryDirectory(
            prefix="koreader-appliance-stage-"
        ) as temporary:
            extracted = Path(temporary)
            with zipfile.ZipFile(archive_path) as archive:
                archive.extractall(extracted, members=_safe_zip_members(archive))
            source = _find_koreader_root(extracted)
            shutil.copytree(source, staging, copy_function=shutil.copyfile)

        # The verified backup fills gaps after a factory reset. Any live state is
        # newer and wins, while the repository overlay remains authoritative.
        _copy_state(state_source, staging)
        _copy_state(destination, staging)
        _copy_onboard_overlay(staging, device)
        if syncthing_plugin is not None and syncthing_binary is not None:
            _install_syncthing(staging, syncthing_plugin, syncthing_binary)
        if not (staging / "reader.lua").is_file() or not (
            staging / "koreader.sh"
        ).is_file():
            raise SafetyError("staged KOReader tree is incomplete")

        marker = staging / DEPLOYMENT_MARKER
        marker.write_text(
            json.dumps(
                deployment_record(
                    device,
                    archive_hash,
                    launch_mode,
                    syncthing_plugin_hash,
                    syncthing_binary_hash,
                    state_backup_sha256,
                ),
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )
        _fsync_tree(staging)
        _activate_staging(staging, destination)

    trigger = under(mount, device.storage.installer_trigger)
    _atomic_copy(root_package, trigger)

    source_hash = _sha256(root_package)
    staged_hash = _sha256(trigger)
    if source_hash != staged_hash:
        raise OSError("root package changed while staging")

    books_root = under(mount, device.storage.books_root)
    for directory in folders:
        (books_root / directory).mkdir(parents=True, exist_ok=True)
    if (
        library_source is not None
        and library_sha256 is not None
        and not library_is_current(mount, library_sha256)
    ):
        _restore_library(mount, books_root, library_source, library_sha256)

    staged_settings = "not-requested"
    if settings is not None:
        settings = settings.expanduser().resolve()
        if not settings.is_file():
            raise SafetyError(f"KOReader settings profile is not readable: {settings}")
        settings_target = destination / (
            "settings.reader.lua.pending"
            if launch_mode == "autostart"
            else "settings.reader.lua"
        )
        if launch_mode == "nickelmenu" and settings_target.exists():
            staged_settings = "preserved-existing"
        else:
            _atomic_copy(settings, settings_target)
            staged_settings = str(settings_target)

    authorized_keys = None
    if authorized_key is not None:
        authorized_keys = destination / "settings/SSH/authorized_keys"
        _atomic_text(authorized_keys, read_authorized_key(authorized_key))

    launcher_config = "not-applicable"
    if device.platform == "kobo" and launch_mode == "nickelmenu":
        launcher = under(mount, ".adds/nm/koreader")
        _atomic_text(launcher, NICKELMENU_CONFIG)
        launcher_script = under(
            mount, ".adds/koreader-appliance/koreader-launch.sh"
        )
        _atomic_text(launcher_script, NICKELMENU_LAUNCHER)
        obsolete = under(mount, ".adds/nm/koreader-launch.sh")
        obsolete.unlink(missing_ok=True)
        obsolete.with_name("._" + obsolete.name).unlink(missing_ok=True)
        _set_ini_value(
            under(mount, ".kobo/Kobo/Kobo eReader.conf"),
            "FeatureSettings",
            "ExcludeSyncFolders",
            EXCLUDE_SYNC_FOLDERS,
        )
        _set_ini_value(
            under(mount, ".kobo/Kobo/Kobo eReader.conf"),
            "ApplicationPreferences",
            "SideloadedMode",
            "true",
        )
        launcher_config = str(launcher)

    _remove_macos_metadata(mount)

    ssh_enabled = None
    if device.platform == "kobo" and launch_mode == "autostart":
        ssh_enabled = under(mount, ".kobo/ssh-enabled")
        ssh_enabled.write_text(
            "Key-only SSH enabled by koreader-appliance.\n",
            encoding="utf-8",
        )
        fsync_file(ssh_enabled)
    return {
        "koreader_root": str(destination),
        "installer_trigger": str(trigger),
        "installer_sha256": staged_hash,
        "ssh_enabled_marker": str(ssh_enabled)
        if ssh_enabled is not None
        else "not-applicable",
        "launch_mode": launch_mode,
        "launcher_config": launcher_config,
        "redeployed": str(redeployed).lower(),
        "authorized_keys": str(authorized_keys)
        if authorized_keys is not None
        else "not-requested",
        "settings_pending": staged_settings,
    }
